# packaging/RecallScore.spec
# PyInstaller spec for the Windows onedir build of Recall Score (M2,
# NFR-02 AC-02.1/AC-02.3). Bundles the FluidSynth DLLs (bin/) and SoundFont
# (soundfonts/) that are gitignored in the working tree (see CLAUDE.md -
# "Local binaries (never commit these)") so the installed app needs no
# separate download - `audio/synth_engine.py`'s PROJECT_ROOT/BIN_DIR
# resolution already works unmodified here: PyInstaller fakes __file__ for
# frozen modules to a path under sys._MEIPASS matching the source tree, so
# dirname(dirname(audio/synth_engine.py)) still lands on the bundle root
# where these datas are placed below.
#
# Runnable directly: .venv\Scripts\python.exe -m PyInstaller
# packaging\RecallScore.spec --noconfirm (from the repo root, so dist\ and
# build\ land there - packaging/installer.nsi expects dist\RecallScore).
# packaging/build_installer.ps1 is an optional convenience wrapper that also
# invokes NSIS afterwards; this spec needs nothing from it.

import glob
import os

from PyInstaller.utils.hooks import collect_data_files

REPO_ROOT = os.path.abspath(os.path.join(SPECPATH, ".."))
PACKAGING_DIR = SPECPATH

datas = [
    (os.path.join(REPO_ROOT, "bin", "*.dll"), "bin"),
    (os.path.join(REPO_ROOT, "soundfonts", "FluidR3_GM.sf2"), "soundfonts"),
    # Click metronome/position announcer sounds (Ref 14/28, tasks.txt
    # E11/D-14) - unlike FluidR3_GM.sf2 above, this one IS checked into
    # git (.gitignore has an explicit exception for it - it's a few
    # hundred KB, project-authored via tools/wav_to_sf2.py, not a 148 MB
    # third-party download) but still needs bundling explicitly since
    # audio/synth_engine.py resolves it via the same
    # PROJECT_ROOT/soundfonts/ path as the main soundfont.
    (os.path.join(REPO_ROOT, "soundfonts", "recall_score_sounds.sf2"), "soundfonts"),
    # No .sf2.json sidecar to bundle alongside it (unlike an earlier version
    # of this spec) - SynthEngine no longer reads one, see
    # audio/synth_engine.py's play_click() comment.
    # Checked into git (unlike bin/soundfonts above) - regenerated by hand
    # with `pandoc docs/user_guide.md -s --toc --metadata
    # title="Recall Score User Guide" -o docs/user_guide.html` whenever the
    # .md source changes; opened from the Help menu (main_window.py
    # user_guide_html_path()/_show_user_guide).
    (os.path.join(REPO_ROOT, "docs", "user_guide.html"), "docs"),
    # version.py reads this at both dev-time and (once bundled here) at
    # frozen-runtime - see version.py's own module docstring.
    (os.path.join(REPO_ROOT, "version.txt"), "."),
]

# Bundled example scores (main_window.py examples_dir(), File > Open Example
# Score...) - a git-tracked folder the user drops MusicXML files into
# directly, unlike bin/soundfonts above. Guarded like icon_path/has_icon
# below: today's folder holds only a placeholder README, so an empty glob
# must not break the build - the next build after real files land picks
# them up automatically, no script changes needed. Three explicit
# extensions (not a bare "examples/*") so the README itself isn't bundled
# alongside the actual scores.
for pattern in ("*.xml", "*.musicxml", "*.mxl"):
    matches = glob.glob(os.path.join(REPO_ROOT, "examples", pattern))
    if matches:
        datas.append((os.path.join(REPO_ROOT, "examples", pattern), "examples"))

# music21 ships its example-score corpus as package data (~58 MB) - the app
# only ever calls converter.parse() on the user's own file, never
# music21.corpus, so it's excluded to keep the installer size down.
datas += collect_data_files(
    "music21",
    excludes=["corpus/**", "test/**", "languageExcerpts/**"],
)

# Dropped in by the user (see main.py's _app_icon_path()) - optional, the
# build works without it.
icon_path = os.path.join(PACKAGING_DIR, "RecallScore.ico")
has_icon = os.path.exists(icon_path)
if has_icon:
    datas.append((icon_path, "."))

# Windows exe version resource, regenerated fresh from version.txt on every
# run - not tracked in git (packaging/build_installer.ps1 used to do this
# from version.py; now this spec does it directly from version.txt so the
# spec can be run standalone, no wrapper script required).
with open(os.path.join(REPO_ROOT, "version.txt"), "r", encoding="utf-8") as f:
    APP_VERSION = f.read().strip()
_version_octets = (APP_VERSION.split(".") + ["0", "0", "0", "0"])[:4]
_file_vers = tuple(int(part) for part in _version_octets)

version_file = os.path.join(PACKAGING_DIR, "version_info.txt")
with open(version_file, "w", encoding="utf-8") as f:
    f.write(f"""VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={_file_vers!r},
    prodvers={_file_vers!r},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo(
      [
      StringTable(
        u'040904B0',
        [StringStruct(u'FileDescription', u'Recall Score - accessible music score and tab viewer'),
        StringStruct(u'FileVersion', u'{APP_VERSION}'),
        StringStruct(u'InternalName', u'RecallScore'),
        StringStruct(u'OriginalFilename', u'RecallScore.exe'),
        StringStruct(u'ProductName', u'Recall Score'),
        StringStruct(u'ProductVersion', u'{APP_VERSION}')])
      ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
""")
has_version_file = True

a = Analysis(
    [os.path.join(REPO_ROOT, "main.py")],
    pathex=[REPO_ROOT],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    # music21 declares matplotlib as a hard dependency for its graph/
    # audioSearch plotting modules (music21/graph/primitives.py,
    # music21/audioSearch/*.py) - this app never imports either, only
    # converter.parse()/tempo/key/meter, so excluding them (and PIL, which
    # matplotlib itself pulls in) keeps ~100+ MB of unused plotting code out
    # of the installer.
    excludes=["matplotlib", "mpl_toolkits", "PIL"],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="RecallScore",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=icon_path if has_icon else None,
    version=version_file if has_version_file else None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name="RecallScore",
)
